# Generated by Django 5.0.6 on 2024-06-12 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table1",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("region_name", models.CharField(max_length=255)),
                ("financial_year", models.CharField(max_length=255)),
                ("month", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Table1",
                "db_table": "exportexcel_table1",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Table2",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("public", models.IntegerField()),
                ("private", models.IntegerField()),
                ("rural", models.IntegerField()),
                ("urban", models.IntegerField()),
                ("total", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.BigIntegerField(blank=True, null=True)),
                (
                    "mapone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Plot.table1"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Table1",
                "db_table": "exportexcel_table2",
                "managed": True,
            },
        ),
    ]
